version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      SERVER_NAME: mikewest
      ELASTICSEARCH_HOSTS: http://stories.elasticsearch.int.staging.zignallabs.com:80
