version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres 
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
